default:
  image: node:latest

build:
  stage: build
  script:
    - cd frontend
    - npm install
    - npm run build

deploy:
  image: alpine:latest
  stage: deploy
  script:
    - apk add --no-cache openssh
    - mkdir -p /.ssh
    - echo "$SSH_PRIVATE_KEY" >> /.ssh/id_rsa
    - chmod 600 /.ssh/id_rsa
    - scp -i /.ssh/id_rsa -o StrictHostKeyChecking=no -r frontend/dist/* devtools-520@vps2644.directvps.nl:public_html/
